<a href="https://colab.research.google.com/github/radenariq/MACHINE-LEARNING/blob/main/JOBSHEET1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)


data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

data = np.array(data)
print('Data Asli')
print(data)

scaler = MinMaxScaler()
scaled = scaler.fit_transform(data)

print('Data Normalisasi')
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)


data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

data = np.asarray(data)
print('Data Asli')
print(data)

scaler = StandardScaler()
scaled = scaler.fit_transform(data)

print('Data Normalisasi')
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


In [5]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarata'],
    ['Politeknik Negeri Semarang']
]

transform_oe = oe.fit_transform(data)
print('Data Asli')
print(data)

print('Data Transformasi Ordinal Encoder')
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


In [6]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarata'],
    ['Politeknik Negeri Semarang']
]

transform_ohe = ohe.fit_transform(data)
print('Data Asli')
print(data)

print('Data Transformasi One Hot Encoder')
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi One Hot Encoder
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [7]:
from sklearn.preprocessing import OneHotEncoder

de = OneHotEncoder(drop='first')

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarata'],
    ['Politeknik Negeri Semarang']
]

transform_de = de.fit_transform(data)
print('Data Asli')
print(data)

print('Data Transformasi Drop Encoder')
print(transform_de.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarata'], ['Politeknik Negeri Semarang']]
Data Transformasi Drop Encoder
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [8]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(stop_words='english')

resp = vect.fit_transform(corpus)
print(resp)

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


In [10]:
vect.get_feature_names_out()

array(['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse',
       'ran', 'saw', 'story', 'tiny'], dtype=object)

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

vect = TfidfVectorizer(stop_words='english')

resp = vect.fit_transform(corpus)
print('Hasil TF-IDF')
print(resp)

print('Hasil Token')
print(vect.get_feature_names_out())

Hasil TF-IDF
  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
Hasil Token
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']
